# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    branches:
        include:
            - master
            - develop
    paths:
        include:
            - src

pool:
    vmImage: "windows-latest"

variables:
    ${{ if not(eq(variables['Build.SourceBranchName'], 'develop')) }}:
        VersionSuffixSwitch: ""
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
        VersionSuffixSwitch: "-VersionSuffix beta"

workspace:
    clean: all

steps:
    - task: UseDotNet@2
      inputs:
          packageType: "sdk"
          useGlobalJson: true

    - task: PowerShell@2
      inputs:
          filePath: "Scripts/build.ps1"
          arguments: "$(VersionSuffixSwitch)"

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: "artifacts/nuget"
          ArtifactName: "drop"
          publishLocation: "Container"
