name: CI

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        name: Update NuGet package
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Setup .NET Core @ Latest
              uses: actions/setup-dotnet@v1
              with:
                  source-url: https://nuget.pkg.github.com/<organization>/index.json
                  dotnet-version: |
                      6.0.x
                      7.0.x
              env:
                  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Build solution and generate NuGet package
              shell: pwsh
              run: ./Scripts/build.ps1

            - name: Push generated package to GitHub registry
              run: dotnet nuget push artifacts/nuget/*.nupkg --skip-duplicate --no-symbols --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
